# -*- coding: utf-8 -*-
"""inteligencia_artificial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rMdvT1JK--7oZSiImqRZJjgpyqPx7XYu

**Inteligência Artificial | Reconhecimento de Expressão Facial**
"""

import cv2
import numpy as np
import pandas as pd
from google.colab.patches import cv2_imshow
import zipfile

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x

import tensorflow
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array
tensorflow.__version__

from google.colab import drive
drive.mount('/content/gdrive')

path ="/content/gdrive/My Drive/Material.zip"
zip_object = zipfile.ZipFile(file = path, mode = "r")
zip_object.extractall('./')
zip_object.close

imagem = cv2.imread('Material/testes/teste_eduardo2.jpeg')
cv2_imshow(imagem)

imagem.shape

cascade_faces = "Material/haarcascade_frontalface_default.xml"
caminho_modelo = "Material/modelo_01_expressoes.h5"
face_detection = cv2.CascadeClassifier(cascade_faces)
classificador_emocoes = load_model(caminho_modelo, compile = False)
expressoes = ["Raiva", "Nojo", "Medo", "Feliz", "Triste", "Surpreso", "Neutro"]

original = imagem.copy()
faces = face_detection.detectMultiScale(original, scaleFactor = 1.1,
                                        minNeighbors = 3, minSize = (20,20))

faces

len(faces)

faces.shape

cinza = cv2.cvtColor(original, cv2.COLOR_BGR2GRAY)
cv2_imshow(cinza)

cinza.shape

roi = cinza[30:30 + 190, 10:10 + 190]

cv2_imshow(roi)

roi.shape

roi

roi = cv2.resize(roi, (48, 48))
cv2_imshow(roi)

roi.dtype

roi = roi.astype('float')
roi.dtype

roi

roi = roi / 255

roi

roi = img_to_array(roi)

roi

roi.shape

roi = np.expand_dims(roi, axis = 0)

roi.shape

"""**Previsões**"""

preds = classificador_emocoes.predict(roi)[0]

preds

len(preds)

emotion_probability = np.max(preds)
emotion_probability

preds.argmax()

label = expressoes[preds.argmax()]

label

"""**Resultados**"""

cv2.putText(original, label, (35,57 -10), cv2.FONT_HERSHEY_SIMPLEX, 0.69,
            (0, 255, 0), 2, cv2.LINE_AA)
cv2.rectangle(original, (35, 57), (35 + 128, 57 + 128), (0, 255, 0), 2)
cv2_imshow(original)